### ISSUE TITLE
Allow custom multicall addresses in Init

### ISSUE THREAD

**Issue by JoeyKhd** [Destiner/ethcall#159]
![image](https://user-images.githubusercontent.com/23193015/203997723-dad6af93-aa6f-4641-9ba6-b7521f8bebc6.png)

As of now the multicall deployment addresses must be specified in multicall.ts based on the CHAIN_ID. Which is fine as defaults.
But for example if one wants to deploy to a local blockchain (Ganache, Hardhat) or any other non public listed private blockchain it cant really be used.

Would you guys consider making this an option in the future?

**Comment by Destiner** [comment]
Hey @JoeyKhd. Sounds like a good idea, will probably implement this in the next major version

**Comment by liron-navon** [comment]
@Destiner It's really hard to write unit tests to functions which use ethcall, I use waffle to deploy my contracts for testing but I cannot tell ethcall which contract to use, so the best chance I had was the deployless multicall, which fails in CI/CD (github actions).

**Comment by Destiner** [comment]
Fixed in `5.0.1`, using `config` param in `Provider` constructor.
