### ISSUE TITLE
package.json has wrong exports

### ISSUE THREAD

**Issue by envin3** [Destiner/ethcall#254]
[package.json exports ](https://github.com/Destiner/ethcall/blob/master/package.json#L17) should be a relative path (https://webpack.js.org/guides/package-exports/).

`"exports": "dist/index.js",`

should be

`"exports": "./dist/index.js",`

This leads to compilations errors when included in jest testing.

**Comment by taariq** [comment]
@Destiner Any time to peek at this, ser?

**Comment by Destiner** [comment]
Good catch, fixed in `6.0.6`
