### ISSUE TITLE
Multicall2 support

### ISSUE THREAD

**Issue by penandlim** [Destiner/ethcall#6]
Makerdao has updated their multicall repo with a newer version of multicall contract called `Multicall2`
https://github.com/makerdao/multicall/blob/master/src/Multicall2.sol

The newer multicall contract adds various new functions but the most important feature is that there is a `tryAggregate` function which allows ignoring any reverted calls. 

Ideally, `ethcall` should move towards supporting the new contract without changing any of the user facing functions. I've kicked off the PR to do so here.  https://github.com/Destiner/ethcall/pull/5

**Comment by penandlim** [comment]
@Destiner Pinging for review on this PR #5

**Comment by Destiner** [comment]
Fixed by #5.
