### ISSUE TITLE
Use v3 for "all"/"tryAll" when possible

### ISSUE THREAD

**Issue by Destiner** [Destiner/ethcall#75]
Currently, Multicall V1 is used for `all` calls, V2 is used for `tryAll`, and V3 is used for `tryEach`. However, V3 brings some gas optimisations, and it makes sense to use it for all calls.

One gotcha to keep in mind is that V3 may be not available for a given chain (not deployed) or a given block (`block < multicall3DeploymentBlock`). In those cases, we need to fallback to V1/V2.

**Comment by jahvi** [comment]
Is it worth worry about adding a fallback if you go for a major version bump? People will still be able to use v4.X if they need multicall v1/v2 support or am I oversimplifying it?

**Comment by Destiner** [comment]
I guess it’s technically viable, but I don’t want to cut out part of the functionality even with a major bump.

**Comment by Destiner** [comment]
Fixed in `4.5.0`.
