### ISSUE TITLE
Feature request: add support for 'pending' blockTag

### ISSUE THREAD

**Issue by alexdupre** [Destiner/ethcall#82]
Current multicall calls accept a `block` number as optional parameter, otherwise they use the default 'latest' block number.
The issue is that metamask has a 20 seconds cache on 'latest' block, so for fast EVM blockchains it's sometimes useful to be able to make calls with 'pending' block number to bypass the metamask cache and get up-to-date results.

**Comment by Destiner** [comment]
Good idea. Added in `4.6.0`.
