### ISSUE TITLE
Add arbitrum testnet 421611

### ISSUE THREAD

**Issue by odcey** [Destiner/ethcall#88]
I would like to add a multicall config for Arbitrum testnet:
chainId: `421611`
Contract: `0x96DB1F8055074aB62161B6Ad66Ab6B8679513DeF`

I tried to do a fork and tried to compile on my project but had problems building
If someone could try and merge, would be awesome !

If needed i can do a pull request but i don't know if it only needs to be added in `multicall.ts`

Thanks !

**Comment by Destiner** [comment]
Hey @odcey. You're right that you only need to add contract address to the `multicall.ts`. You can try forking via GitHub web UI: open [this file](https://github.com/Destiner/ethcall/blob/master/src/multicall.ts) and click pen icon on the right.

**Comment by odcey** [comment]
@Destiner i opened a pull request to add arbitrum testnet based on the conversation above

**Comment by Destiner** [comment]
Thanks, added in `4.6.5`.
