### ISSUE TITLE
getEthBalance(address) function is stale

### ISSUE THREAD

**Issue by alexdupre** [Destiner/ethcall#91]
The implementation of the `getEthBalance(address)` function seems stale, it supports only multicall1 (and checks for provider that is not needed anymore): https://github.com/Destiner/ethcall/blob/master/src/provider.ts#L47-L55

It's possible to use directly the same call exported by the `calls` API as a workaround, but I guess the one in the `provider` should work as well.

**Comment by Destiner** [comment]
Hey @alexdupre, thanks for feedback! Fixed in `4.6.4`.
